### PR TITLE
Update plugin to work with XOOM and grab css class from select and option's.

### PR DESCRIPTION
**Pull request by codeBelt**
Added jQuery to the Immediately Invoked Function to protect the $ alias.
Add logic to allow plugin to work on other mobile devices and not just IOS. Specifically the XOOM.
Rename isSafariMobile to isMobile.
Add webkit-overflow-scrolling to css so it has the nice ISO native scrolling.
Make plugin add the css class names from the select and option tags.
If the option is already selected then we add the selected class to the li element.

### CODE REVIEW

**Comment by sylvain-hamel** [comment]
Hi @codeBelt,

Thanks for your contribution. When wrote this it was especially for iOS. I don't recall having the same problem on Android. Can you confirm that Android does not support multiline selects? I don't know about XOOM, I did not test on that device.

Maybe it would be more flexible if the UserAgent test string was passed as a parameter:

``` javascript
$().ready(function () {
    $("select").fixForSafariMobile("Android|webOS|iPhone|iPad|iPod|BlackBerry");
})
```

If we do that, I might as well rename the project `mobile-multiline-select` or even just `multiline-select-override`.

Questions? Comments?
- Sly

**Comment by codeBelt** [comment]
I know the issue is specifically on the iPad and Motorola Xoom (Android 4.x) so I think calling it mobile-multiline-select would be good. I like your idea of passing the "Android|webOS|iPhone|iPad|iPod|BlackBerry" as a parameter but there should be some sort of default. Maybe the default is just IOS? I also like how you are accepting a Boolean so you can test with in on desktop browsers so you should also keep that functionality.

**Comment by sylvain-hamel** [comment]
ok. Are you willing to make these changes and send me a new PR? Otherwise, it might take a while before I get to doing them.

**Comment by codeBelt** [comment]
Not sure if I can do it anytime soon either. I am working on a few other things right now.

**Pull request closed without merging**
